version: '3'
services:
  postgresql:
    image: postgres:11
    container_name: postgresql_shoppingcart
    environment:
      POSTGRES_PASSWORD: Local123
      POSTGRES_DB: shoppingcartDB
    volumes:
      - ../ci/dbapgsql/:/app/pg/
      - ./docker-data/postgres/:/data/
    ports:
      - "5432:5432"
    restart: always